<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.29.3" />
    <PackageReference Include="Grpc.Tools" Version="2.69.0" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="../../../Proto/Control/Common/ClusterCommon.proto" ProtoRoot="../../../Proto" GrpcServices="None" />
    <Protobuf Include="../../../Proto/Control/Inner/CoordinatorInner.proto" ProtoRoot="../../../Proto" GrpcServices="None" />
    <Protobuf Include="../../../Proto/Business/Inner/Database.proto" ProtoRoot="../../../Proto" GrpcServices="None" />
  </ItemGroup>
</Project>
