<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <ProjectReference Include="../Shared/MiniCore.Server.Protocol/MiniCore.Server.Protocol.csproj" />
    <ProjectReference Include="../Shared/MiniCore.Server.Rpc/MiniCore.Server.Rpc.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
  </ItemGroup>
</Project>
