using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using MiniCore.UI;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEditor.Callbacks;
using UnityEngine;
using UnityEngine.UI;
using YooAsset.Editor;

namespace MiniCore.EditorTools.UI
{
    /// <summary>
    /// 从 AUIWindowView 内置配置生成强类型路由和无反射运行时注册表。
    /// </summary>
    public static class UIWindowRegistryGenerator
    {
        #region Private 私有成员

        private const string GeneratedHeader = "// Auto-generated by UIWindowRegistryGenerator. Do not modify by hand.\n";

        #endregion

        #region Public 公共成员

        /// <summary>
        /// 从菜单手动生成窗口注册表，并在 Console 输出明确的执行结果。
        /// </summary>
        [MenuItem("MiniCore/UI/Generate Window Registry", priority = 2001)]
        private static void GenerateFromMenu()
        {
            try
            {
                int windowCount = GenerateInternal(out bool changed);
                string state = changed ? "已更新生成文件" : "生成文件已是最新";
                Debug.Log(
                    $"UI Window Registry 生成成功：共 {windowCount} 个窗口，{state}。\n" +
                    $"Routes: {UIAuthoringUtility.RoutesPath}\nRegistry: {UIAuthoringUtility.RegistryPath}");
            }
            catch (Exception exception)
            {
                Debug.LogError($"UI Window Registry 生成失败：{exception.Message}");
            }
        }

        /// <summary>
        /// 校验全部窗口并覆盖生成路由和直接构造注册表。
        /// </summary>
        public static void Generate()
        {
            GenerateInternal(out _);
        }

        /// <summary>
        /// 扫描窗口 Prefab，并返回窗口数量与生成文件是否发生变化。
        /// </summary>
        /// <param name="changed">是否写入了新的生成内容。</param>
        /// <returns>成功收集的窗口数量。</returns>
        private static int GenerateInternal(out bool changed)
        {
            if (!TryCollect(out List<UIWindowGenerationInfo> windows, out string error))
            {
                throw new InvalidOperationException(error);
            }

            string routes = BuildRoutes(windows);
            string registry = BuildRegistry(windows);
            changed = UIAuthoringUtility.WriteGeneratedFile(UIAuthoringUtility.RoutesPath, routes);
            changed |= UIAuthoringUtility.WriteGeneratedFile(UIAuthoringUtility.RegistryPath, registry);
            if (changed)
            {
                AssetDatabase.Refresh();
            }

            return windows.Count;
        }

        /// <summary>
        /// 验证 View Authoring、Prefab、类型、身份、地址和生成文件一致性。
        /// </summary>
        /// <param name="error">首个确定性错误。</param>
        /// <returns>当前项目可安全构建时返回 true。</returns>
        public static bool Validate(out string error)
        {
            if (!TryCollect(out List<UIWindowGenerationInfo> windows, out error))
            {
                return false;
            }

            string expectedRoutes = BuildRoutes(windows);
            string expectedRegistry = BuildRegistry(windows);
            if (!File.Exists(Path.GetFullPath(UIAuthoringUtility.RoutesPath)) ||
                !string.Equals(File.ReadAllText(Path.GetFullPath(UIAuthoringUtility.RoutesPath)), expectedRoutes, StringComparison.Ordinal))
            {
                error = "UIWindowRoutes.Generated.cs 已过期，请执行 MiniCore/UI/Generate Window Registry。";
                return false;
            }

            if (!File.Exists(Path.GetFullPath(UIAuthoringUtility.RegistryPath)) ||
                !string.Equals(File.ReadAllText(Path.GetFullPath(UIAuthoringUtility.RegistryPath)), expectedRegistry, StringComparison.Ordinal))
            {
                error = "ProjectUIWindowRegistration.Generated.cs 已过期，请执行 MiniCore/UI/Generate Window Registry。";
                return false;
            }

            if (!ValidateYooAssetCollection(windows, out error))
            {
                return false;
            }

            error = null;
            return true;
        }

        /// <summary>
        /// 用不引用任何 View 或 Presenter 的安全内容使旧注册表失效。
        /// </summary>
        public static void InvalidateRegistry()
        {
            UIAuthoringUtility.WriteGeneratedFile(UIAuthoringUtility.RegistryPath, BuildRegistry(new List<UIWindowGenerationInfo>()));
        }

        #endregion

        #region Private 私有成员

        /// <summary>
        /// 扫描窗口 Prefab 并完成所有构建前约束检查。
        /// </summary>
        /// <param name="windows">有效窗口信息。</param>
        /// <param name="error">首个失败说明。</param>
        /// <returns>全部窗口有效时返回 true。</returns>
        private static bool TryCollect(out List<UIWindowGenerationInfo> windows, out string error)
        {
            windows = new List<UIWindowGenerationInfo>();
            HashSet<UIWindowId> ids = new HashSet<UIWindowId>();
            HashSet<string> routes = new HashSet<string>(StringComparer.Ordinal);
            HashSet<string> addresses = new HashSet<string>(StringComparer.Ordinal);
            string[] guids = AssetDatabase.FindAssets("t:Prefab", UIAuthoringUtility.WindowSearchRoots);
            bool hasUndiscoveredPrefabs = false;
            for (int rootIndex = 0; rootIndex < UIAuthoringUtility.WindowSearchRoots.Length; rootIndex++)
            {
                string windowsFullPath = Path.GetFullPath(UIAuthoringUtility.WindowSearchRoots[rootIndex]);
                hasUndiscoveredPrefabs |= Directory.Exists(windowsFullPath) && Directory.GetFiles(windowsFullPath, "*.prefab", SearchOption.AllDirectories).Length > 0;
            }

            if (guids.Length == 0 && hasUndiscoveredPrefabs)
            {
                error = "AssetDatabase 尚未完成 UI Windows 导入，保留现有生成表并等待下一次脚本重载。";
                return false;
            }

            Array.Sort(guids, StringComparer.Ordinal);
            for (int i = 0; i < guids.Length; i++)
            {
                string path = AssetDatabase.GUIDToAssetPath(guids[i]);
                GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                if (!TryCreateInfo(prefab, path, out UIWindowGenerationInfo info, out error))
                {
                    return false;
                }

                if (!ids.Add(info.Id))
                {
                    error = $"窗口 WindowId 重复：{info.RouteName}，路径 {path}。";
                    return false;
                }

                if (!routes.Add(info.RouteName))
                {
                    error = $"窗口 RouteName 重复：{info.RouteName}。";
                    return false;
                }

                if (!addresses.Add(info.Address))
                {
                    error = $"窗口 YooAsset 地址重复：{info.Address}。";
                    return false;
                }

                windows.Add(info);
            }

            windows.Sort((left, right) => string.CompareOrdinal(left.RouteName, right.RouteName));
            error = null;
            return true;
        }

        /// <summary>
        /// 校验一个 Prefab 并创建代码生成信息。
        /// </summary>
        /// <param name="prefab">窗口 Prefab。</param>
        /// <param name="path">Prefab 资产路径。</param>
        /// <param name="info">有效生成信息。</param>
        /// <param name="error">失败说明。</param>
        /// <returns>Prefab 满足运行时约束时返回 true。</returns>
        private static bool TryCreateInfo(GameObject prefab, string path, out UIWindowGenerationInfo info, out string error)
        {
            info = default;
            if (prefab == null)
            {
                error = $"无法加载 UI Prefab：{path}。";
                return false;
            }

            AUIWindowView view = prefab.GetComponent<AUIWindowView>();
            if (view == null)
            {
                error = $"窗口 {path} 根节点必须包含一个 AUIWindowView。";
                return false;
            }

            if (prefab.GetComponents<AUIWindowView>().Length != 1)
            {
                error = $"窗口 {path} 根节点只能包含一个 AUIWindowView。";
                return false;
            }

            if (prefab.GetComponent<Canvas>() != null)
            {
                error = $"普通窗口根节点禁止携带 Canvas：{path}。特殊子 Canvas 请在子节点挂载 UISubCanvas。";
                return false;
            }

            if (!(prefab.transform is RectTransform))
            {
                error = $"窗口 {path} 的根节点必须使用 RectTransform。";
                return false;
            }

            Canvas[] nestedCanvases = prefab.GetComponentsInChildren<Canvas>(true);
            for (int i = 0; i < nestedCanvases.Length; i++)
            {
                if (nestedCanvases[i].GetComponent<UISubCanvas>() == null)
                {
                    error = $"窗口 {path} 的子 Canvas {nestedCanvases[i].name} 未声明 UISubCanvas。";
                    return false;
                }
            }

            if (prefab.GetComponent<CanvasGroup>() == null)
            {
                error = $"窗口 {path} 缺少 CanvasGroup，请保存 Prefab 触发自动补件。";
                return false;
            }

            UISafeAreaPolicy safeAreaPolicy = ResolveSafeAreaPolicy(view.SafeAreaPolicy);
            if (safeAreaPolicy == UISafeAreaPolicy.Inherit)
            {
                error = $"窗口 {path} 无法解析 Inherit 安全区域策略，请检查 UIProjectProfile。";
                return false;
            }

            if (safeAreaPolicy == UISafeAreaPolicy.ConstrainContent && view.SafeAreaTarget == null)
            {
                error = $"窗口 {path} 使用 ConstrainContent，但未配置 SafeAreaTarget。";
                return false;
            }

            if (view.TransitionDriver != null && view.GetTransitionDriver() == null)
            {
                error = $"窗口 {path} 的 Transition Driver 未实现 IUITransitionDriver：{view.TransitionDriver.GetType().FullName}。";
                return false;
            }

            UIWindowId id = view.GetWindowId();
            if (id.IsEmpty)
            {
                error = $"窗口 {path} 的 WindowId 非法。";
                return false;
            }

            string routeName = SanitizeIdentifier(view.RouteName);
            if (!string.Equals(routeName, view.RouteName, StringComparison.Ordinal) || string.IsNullOrEmpty(routeName))
            {
                error = $"窗口 {path} 的 RouteName 必须是合法且无需修正的 C# 标识符：{view.RouteName}。";
                return false;
            }

            string address = Path.GetFileNameWithoutExtension(path);
            if (!string.Equals(view.AssetAddress, address, StringComparison.Ordinal))
            {
                error = $"窗口 {path} 的自动地址应为 {address}，请重新保存 Prefab。";
                return false;
            }

            Type logicType = UIAuthoringUtility.ResolveType(view.LogicTypeName);
            if (logicType == null || !typeof(IUIWindowLogic).IsAssignableFrom(logicType) || logicType.IsAbstract || logicType.GetConstructor(Type.EmptyTypes) == null)
            {
                error = $"窗口 {path} 的 Presenter 无效或不可直接构造：{view.LogicTypeName}。";
                return false;
            }

            info = new UIWindowGenerationInfo(
                id,
                routeName,
                address,
                view.GetType(),
                logicType,
                view.RenderSpace,
                view.Layer,
                view.InstancePolicy,
                view.DuplicateOpenPolicy,
                view.CachePolicy,
                view.SafeAreaPolicy,
                view.Modal,
                view.CloseOnMaskClick,
                view.MaxCacheCount,
                view.NavigationGroup);
            error = null;
            return true;
        }

        /// <summary>
        /// 使用项目 Profile 解析窗口继承的最终安全区域策略。
        /// </summary>
        /// <param name="policy">窗口序列化策略。</param>
        /// <returns>最终策略；Profile 缺失时保留 Inherit 供调用方报错。</returns>
        private static UISafeAreaPolicy ResolveSafeAreaPolicy(UISafeAreaPolicy policy)
        {
            if (policy != UISafeAreaPolicy.Inherit)
            {
                return policy;
            }

            UIProjectProfile profile = AssetDatabase.LoadAssetAtPath<UIProjectProfile>("Assets/AssetRes/UI/Profiles/UIProjectProfile.asset");
            return profile != null ? profile.DefaultSafeAreaPolicy : UISafeAreaPolicy.Inherit;
        }

        /// <summary>
        /// 生成公共强类型路由标记。
        /// </summary>
        /// <param name="windows">有效窗口集合。</param>
        /// <returns>完整 C# 文件文本。</returns>
        private static string BuildRoutes(List<UIWindowGenerationInfo> windows)
        {
            StringBuilder builder = new StringBuilder(1024);
            builder.Append(GeneratedHeader);
            builder.AppendLine("namespace MiniCore.HotUpdate");
            builder.AppendLine("{");
            for (int i = 0; i < windows.Count; i++)
            {
                UIWindowGenerationInfo window = windows[i];
                builder.AppendLine("    /// <summary>");
                builder.AppendLine($"    /// {window.RouteName} 的强类型窗口路由。");
                builder.AppendLine("    /// </summary>");
                builder.AppendLine($"    public readonly struct {window.RouteName} : global::MiniCore.UI.IUIWindowRoute");
                builder.AppendLine("    {");
                builder.AppendLine("    }");
                builder.AppendLine();
            }

            builder.AppendLine("}");
            return builder.ToString();
        }

        /// <summary>
        /// 验证 UI 运行时收集组以及 Profile、Root、Window 地址确实进入 DefaultPackage。
        /// </summary>
        /// <param name="windows">当前窗口生成信息。</param>
        /// <param name="error">首个收集错误。</param>
        /// <returns>YooAsset 配置和地址完整时返回 true。</returns>
        private static bool ValidateYooAssetCollection(List<UIWindowGenerationInfo> windows, out string error)
        {
            AssetBundleCollectorSetting setting = AssetDatabase.LoadAssetAtPath<AssetBundleCollectorSetting>("Assets/AssetBundleCollectorSetting.asset");
            if (setting == null)
            {
                error = "未找到 YooAsset AssetBundleCollectorSetting.asset。";
                return false;
            }

            try
            {
                AssetBundleCollectorPackage package = setting.GetPackage("DefaultPackage");
                string[] requiredGroups = { "UIFramework", "UIProfiles", "UIWindows" };
                for (int i = 0; i < requiredGroups.Length; i++)
                {
                    bool found = package.Groups.Any(group => string.Equals(group.GroupName, requiredGroups[i], StringComparison.Ordinal));
                    if (!found)
                    {
                        error = $"YooAsset 缺少 UI 收集组：{requiredGroups[i]}。";
                        return false;
                    }
                }

                CollectResult result = setting.BeginCollect("DefaultPackage", false, false);
                HashSet<string> addresses = new HashSet<string>(StringComparer.Ordinal);
                for (int i = 0; i < result.CollectAssets.Count; i++)
                {
                    addresses.Add(result.CollectAssets[i].Address);
                }

                if (!addresses.Contains("ApplicationUIRoot") || !addresses.Contains("UIProjectProfile"))
                {
                    error = "YooAsset 未收集 ApplicationUIRoot 或 UIProjectProfile 地址。";
                    return false;
                }

                for (int i = 0; i < windows.Count; i++)
                {
                    if (!addresses.Contains(windows[i].Address))
                    {
                        error = $"YooAsset 未收集窗口地址：{windows[i].Address}。";
                        return false;
                    }
                }
            }
            catch (Exception exception)
            {
                error = $"YooAsset UI 收集配置无效：{exception.Message}";
                return false;
            }

            error = null;
            return true;
        }

        /// <summary>
        /// 生成直接 GetComponent 和 new 构造的运行时注册表。
        /// </summary>
        /// <param name="windows">有效窗口集合。</param>
        /// <returns>完整 C# 文件文本。</returns>
        private static string BuildRegistry(List<UIWindowGenerationInfo> windows)
        {
            StringBuilder builder = new StringBuilder(4096);
            builder.Append(GeneratedHeader);
            builder.AppendLine("using MiniCore.UI;");
            builder.AppendLine();
            builder.AppendLine("namespace MiniCore.HotUpdate");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine("    /// 将当前项目窗口定义显式注入 AOT UI Runtime。");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine("    public static class ProjectUIWindowRegistration");
            builder.AppendLine("    {");
            builder.AppendLine("        #region Public 公共成员");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 登记当前项目中全部有效窗口。");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        /// <param name=\"registry\">AOT UI Runtime 持有的项目注册表。</param>");
            builder.AppendLine("        public static void Register(UIWindowRegistry registry)");
            builder.AppendLine("        {");
            builder.AppendLine("            if (registry == null)");
            builder.AppendLine("            {");
            builder.AppendLine("                throw new global::System.ArgumentNullException(nameof(registry));");
            builder.AppendLine("            }");
            builder.AppendLine();
            for (int i = 0; i < windows.Count; i++)
            {
                UIWindowGenerationInfo window = windows[i];
                builder.AppendLine("            registry.Register(new UIWindowDefinition(");
                builder.AppendLine($"                new UIWindowId({window.Id.High}UL, {window.Id.Low}UL),");
                builder.AppendLine($"                typeof(global::MiniCore.HotUpdate.{window.RouteName}),");
                builder.AppendLine($"                \"{Escape(window.RouteName)}\",");
                builder.AppendLine($"                \"{Escape(window.Address)}\",");
                builder.AppendLine($"                UIRenderSpace.{window.RenderSpace},");
                builder.AppendLine($"                UILayer.{window.Layer},");
                builder.AppendLine($"                UIInstancePolicy.{window.InstancePolicy},");
                builder.AppendLine($"                UIDuplicateOpenPolicy.{window.DuplicateOpenPolicy},");
                builder.AppendLine($"                UICachePolicy.{window.CachePolicy},");
                builder.AppendLine($"                UISafeAreaPolicy.{window.SafeAreaPolicy},");
                builder.AppendLine($"                {Bool(window.Modal)},");
                builder.AppendLine($"                {Bool(window.CloseOnMaskClick)},");
                builder.AppendLine($"                {window.MaxCacheCount},");
                builder.AppendLine($"                \"{Escape(window.NavigationGroup)}\",");
                builder.AppendLine($"                Resolve{window.RouteName}View,");
                builder.AppendLine($"                Create{window.RouteName}Logic));");
            }

            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        #endregion");
            builder.AppendLine();
            builder.AppendLine("        #region Private 私有成员");
            for (int i = 0; i < windows.Count; i++)
            {
                UIWindowGenerationInfo window = windows[i];
                builder.AppendLine("        /// <summary>");
                builder.AppendLine($"        /// 从 Prefab 根节点直接解析 {window.ViewType.Name}。");
                builder.AppendLine("        /// </summary>");
                builder.AppendLine("        /// <param name=\"instance\">窗口 Prefab 实例。</param>");
                builder.AppendLine("        /// <returns>强类型窗口 View。</returns>");
                builder.AppendLine($"        private static AUIWindowView Resolve{window.RouteName}View(global::UnityEngine.GameObject instance)");
                builder.AppendLine("        {");
                builder.AppendLine($"            return instance.GetComponent<global::{window.ViewType.FullName}>();");
                builder.AppendLine("        }");
                builder.AppendLine();
                builder.AppendLine("        /// <summary>");
                builder.AppendLine($"        /// 直接构造 {window.LogicType.Name}。");
                builder.AppendLine("        /// </summary>");
                builder.AppendLine("        /// <returns>窗口逻辑实例。</returns>");
                builder.AppendLine($"        private static IUIWindowLogic Create{window.RouteName}Logic()");
                builder.AppendLine("        {");
                builder.AppendLine($"            return new global::{window.LogicType.FullName}();");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            builder.AppendLine("        #endregion");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        /// <summary>
        /// 将任意路由文本转换为可比较的 C# 标识符。
        /// </summary>
        /// <param name="value">原始路由文本。</param>
        /// <returns>合法标识符；空文本返回空字符串。</returns>
        private static string SanitizeIdentifier(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return string.Empty;
            }

            StringBuilder builder = new StringBuilder(value.Length);
            for (int i = 0; i < value.Length; i++)
            {
                char character = value[i];
                bool valid = i == 0 ? char.IsLetter(character) || character == '_' : char.IsLetterOrDigit(character) || character == '_';
                if (valid)
                {
                    builder.Append(character);
                }
            }

            return builder.ToString();
        }

        /// <summary>
        /// 转义生成代码中的普通字符串。
        /// </summary>
        /// <param name="value">原始文本。</param>
        /// <returns>C# 字符串内容。</returns>
        private static string Escape(string value)
        {
            return (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        /// <summary>
        /// 输出小写 C# 布尔字面量。
        /// </summary>
        /// <param name="value">布尔值。</param>
        /// <returns>true 或 false。</returns>
        private static string Bool(bool value)
        {
            return value ? "true" : "false";
        }

        #endregion

        #region Private 类型

        /// <summary>
        /// 单个窗口参与代码生成的不可变信息。
        /// </summary>
        private readonly struct UIWindowGenerationInfo
        {
            public readonly UIWindowId Id;
            public readonly string RouteName;
            public readonly string Address;
            public readonly Type ViewType;
            public readonly Type LogicType;
            public readonly UIRenderSpace RenderSpace;
            public readonly UILayer Layer;
            public readonly UIInstancePolicy InstancePolicy;
            public readonly UIDuplicateOpenPolicy DuplicateOpenPolicy;
            public readonly UICachePolicy CachePolicy;
            public readonly UISafeAreaPolicy SafeAreaPolicy;
            public readonly bool Modal;
            public readonly bool CloseOnMaskClick;
            public readonly int MaxCacheCount;
            public readonly string NavigationGroup;

            /// <summary>
            /// 创建窗口生成信息。
            /// </summary>
            public UIWindowGenerationInfo(
                UIWindowId id,
                string routeName,
                string address,
                Type viewType,
                Type logicType,
                UIRenderSpace renderSpace,
                UILayer layer,
                UIInstancePolicy instancePolicy,
                UIDuplicateOpenPolicy duplicateOpenPolicy,
                UICachePolicy cachePolicy,
                UISafeAreaPolicy safeAreaPolicy,
                bool modal,
                bool closeOnMaskClick,
                int maxCacheCount,
                string navigationGroup)
            {
                Id = id;
                RouteName = routeName;
                Address = address;
                ViewType = viewType;
                LogicType = logicType;
                RenderSpace = renderSpace;
                Layer = layer;
                InstancePolicy = instancePolicy;
                DuplicateOpenPolicy = duplicateOpenPolicy;
                CachePolicy = cachePolicy;
                SafeAreaPolicy = safeAreaPolicy;
                Modal = modal;
                CloseOnMaskClick = closeOnMaskClick;
                MaxCacheCount = maxCacheCount;
                NavigationGroup = navigationGroup;
            }
        }

        #endregion
    }
}
