syntax = "proto3";

package minicore.cluster.inner;
option csharp_namespace = "MiniCore.Protocol.Generated";

import "Control/Common/ClusterCommon.proto";

//[IRpcRequest]
message RegisterServerRequest {
  string instance_id = 1;
  uint32 roles = 2;
  string inner_host = 3;
  int32 inner_port = 4;
  string outer_web_socket_url = 5;
  minicore.cluster.common.ClusterServiceKind service_kind = 6;
  string protocol_version = 7;
}

//[IRpcResponse]
message RegisterServerResponse {
  int32 code = 1;
  string msg = 2;
  int64 lease_milliseconds = 3;
  int64 directory_revision = 4;
  repeated minicore.cluster.common.ClusterServiceEndpoint services = 5;
}

//[IRpcRequest]
message ServerHeartbeatRequest {
  string instance_id = 1;
  int64 known_directory_revision = 2;
}

//[IRpcResponse]
message ServerHeartbeatResponse {
  int32 code = 1;
  string msg = 2;
  int64 lease_milliseconds = 3;
  int64 directory_revision = 4;
  repeated minicore.cluster.common.ClusterServiceEndpoint changed_services = 5;
}

//[IRpcRequest]
message SetServerStateRequest {
  string instance_id = 1;
  minicore.cluster.common.ClusterServiceState state = 2;
}

//[IRpcResponse]
message SetServerStateResponse {
  int32 code = 1;
  string msg = 2;
  int64 directory_revision = 3;
}

//[IRpcRequest]
message ResolveInnerServiceRequest {
  minicore.cluster.common.ClusterServiceKind service_kind = 1;
}

//[IRpcResponse]
message ResolveInnerServiceResponse {
  int32 code = 1;
  string msg = 2;
  minicore.cluster.common.ClusterServiceEndpoint endpoint = 3;
}
